#!/bin/python

import sys


n = int(raw_input().strip())
a = []
for a_i in xrange(n):
    a_temp = map(int,raw_input().strip().split(' '))
    a.append(a_temp)
i=0
j=0
sum1=0
sum2=0
n=n-1
while i <= n:
    sum1=sum1 + a[i][j]
    i=i+1
    j=j+1
p=0
q=0
while p <= n:
    sum2=sum2 + a[n-p][q]
    p=p+1
    q=q+1

print abs(sum1-sum2)
